# Generated by Django 6.0.5 on 2026-06-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified_user_password_setup_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_setup_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
