# Generated by Django 6.0.5 on 2026-06-03 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_password_setup_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_setup_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
