# Generated by Django 6.0.5 on 2026-06-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
