# Generated by Django 6.0.5 on 2026-06-18 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BOOK_ADDED', 'Book Added'), ('BOOK_UPDATED', 'Book Updated'), ('BOOK_DELETED', 'Book Deleted'), ('BOOK_ISSUED', 'Book Issued'), ('BOOK_RETURNED', 'Book Returned'), ('BOOK_RENEWED', 'Book Renewed'), ('USER_CREATED', 'User Created'), ('LIBRARIAN_CREATED', 'Librarian Created'), ('PASSWORD_APPROVED', 'Password Approved'), ('PASSWORD_REJECTED', 'Password Rejected'), ('FINE_COLLECTED', 'Fine Collected')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
