# Generated by Django 6.0.5 on 2026-06-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('BOOK_ADDED', 'Book Added'), ('BOOK_UPDATED', 'Book Updated'), ('BOOK_DELETED', 'Book Deleted'), ('BOOK_ISSUED', 'Book Issued'), ('BOOK_RETURNED', 'Book Returned'), ('BOOK_RENEWED', 'Book Renewed'), ('USER_CREATED', 'User Created'), ('LIBRARIAN_CREATED', 'Librarian Created'), ('PASSWORD_APPROVED', 'Password Approved'), ('PASSWORD_REJECTED', 'Password Rejected'), ('FINE_COLLECTED', 'Fine Collected'), ('DEACTIVATION_REQUESTED', 'Deactivation Requested'), ('USER_DEACTIVATED', 'User Deactivated'), ('DEACTIVATION_REJECTED', 'Deactivation Rejected')], max_length=50),
        ),
    ]
