# Generated by Django 6.0.5 on 2026-06-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='fine_per_day',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='issue_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
