# Generated by Django 6.0.5 on 2026-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_issuebook_fine_per_day_issuebook_issue_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='issue_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
